"""add memory_episodes table

Revision ID: d63dc148e7d2
Revises: 4e5c7165dbea
Create Date: 2026-08-29 07:28:23.871112

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd63dc148e7d2'
down_revision: str | None = '4e5c7165dbea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'memory_episodes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('event_time_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('source', sa.Text(), nullable=True),
        sa.Column(
            'valid_from',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            'confidence >= 0 AND confidence <= 1', name='ck_memory_episodes_confidence_range'
        ),
        sa.CheckConstraint(
            'event_time_end IS NULL OR event_time_end >= event_time',
            name='ck_memory_episodes_time_order',
        ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_memory_episodes_event_time'), 'memory_episodes', ['event_time'], unique=False
    )
    op.create_index(
        op.f('ix_memory_episodes_tenant_id'), 'memory_episodes', ['tenant_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_episodes_tenant_id'), table_name='memory_episodes')
    op.drop_index(op.f('ix_memory_episodes_event_time'), table_name='memory_episodes')
    op.drop_table('memory_episodes')
    # ### end Alembic commands ###
